version: '3.4'

services:
  authservice:
    image: fuli1001/arise-authservice:win
    build:
      context: .
      dockerfile: AuthService/Dockerfile.win
    networks:
      - arisenetwork
      
  fileuploadservice:
    image: fuli1001/arise-fileuploadservice:win
    build:
      context: .
      dockerfile: FileUploadService/Dockerfile.win
    networks:
      - arisenetwork
    volumes:
      - C:/Phototgraphy:c:/app/uploaded
      
networks:
  arisenetwork:
