version: '3.4'

services:
  authservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__AuthConnection=Server=47.108.194.52;Database=Arise.Auth;User Id=fuli;Password=fl511304;
    ports:
      - "5105:80"

  fileuploadservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AuthSettings__Authority=http://43.225.159.87:5100
      - AuthSettings__Audience=Arise.FileUploadService
      - StreamingSettings__FileSizeLimit=52428800
      - StreamingSettings__StoredFilesPath=./
    ports:
      - "10010:80"
