version: '3.4'

services:
  authservice:
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=10001
    ports:
      - "10000:80"
      - "10001:443"
  fileuploadservice:
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=54301
      - Auth__Authority=authservice
      - Auth__Audience=Arise.FileUploadService
      - StreamingSettings__FileSizeLimit=52428800
      - StreamingSettings__StoredFilesPath=upload
    ports:
      - "10010:80"
      - "10011:443"
