version: '3.4'

services:
  authservice:
    image: fuli1001/arise-authservice:linux
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    networks:
      - arisenetwork
      
  fileuploadservice:
    image: fuli1001/arise-fileuploadservice:linux
    build:
      context: .
      dockerfile: FileUploadService/Dockerfile
    networks:
      - arisenetwork
    volumes:
      - /var/www/photography:/app/uploaded
      
networks:
  arisenetwork:
